package com.example.fitnessfit.domain.models

data class ExercisePrediction(
    val day1: List<String>,
    val day2: List<String>,
    val day3: List<String>,
    val day4: List<String>,
    val day5: List<String>,
    val day6: List<String>,
    val day7: List<String>,
    val day8: List<String>,
    val day9: List<String>,
    val day10: List<String>,
    val day11: List<String>,
    val day12: List<String>,
    val day13: List<String>,
    val day14: List<String>,
    val day15: List<String>,
    val day16: List<String>,
    val day17: List<String>,
    val day18: List<String>,
    val day19: List<String>,
    val day20: List<String>,
    val day21: List<String>,
    val day22: List<String>,
    val day23: List<String>,
    val day24: List<String>
){
    constructor(): this(
    day1= emptyList(),
    day2= emptyList(),
    day3= emptyList(),
    day4= emptyList(),
    day5= emptyList(),
    day6= emptyList(),
    day7= emptyList(),
    day8= emptyList(),
    day9= emptyList(),
    day10= emptyList(),
    day11= emptyList(),
    day12= emptyList(),
    day13= emptyList(),
    day14= emptyList(),
    day15= emptyList(),
    day16= emptyList(),
    day17= emptyList(),
    day18= emptyList(),
    day19= emptyList(),
    day20= emptyList(),
    day21= emptyList(),
    day22= emptyList(),
    day23= emptyList(),
    day24= emptyList()
    )
}
